-- Schema snapshot for the `notes` table and related objects (Supabase/Postgres)
--
-- Unlike notes_rls_policies.sql (now removed), this file was NOT guessed from
-- documentation. Every definition below was confirmed directly against the
-- live database, by running introspection queries in the Supabase SQL Editor
-- and pasting the results back (information_schema.columns, pg_constraint,
-- pg_indexes, pg_trigger, pg_policies, pg_proc) -- captured 2026-09-15.
--
-- Why this exists instead of a real `supabase db pull` migration: the
-- Supabase CLI's db pull/db dump shell out to a bundled Docker image, and
-- this machine has neither Docker nor Podman installed (and no Homebrew to
-- install them with easily). `supabase init` has already been run in this
-- repo (see supabase/config.toml) and `npx supabase@latest` works fine for
-- everything that doesn't need Docker. If Docker or Podman ever gets
-- installed, prefer completing the real flow:
--   npx supabase@latest login
--   npx supabase@latest link --project-ref yzgyhdrughpwaqgcgqeu
--   npx supabase@latest db pull
-- That generates a CLI-tracked migration under supabase/migrations/ and
-- properly reconciles Supabase's own remote migration-history table -- this
-- file deliberately does NOT live under migrations/ so it's never confused
-- with one, since it was never applied through the CLI.
--
-- If you change the schema before then, update this file by hand to match
-- (or re-run the same introspection queries), the same way you'd keep any
-- other piece of documentation in sync.

-- ============================================================
-- Table: public.notes
-- ============================================================

create table public.notes (
  id bigint generated by default as identity primary key,
  content text not null,
  user_id uuid not null references auth.users (id),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

-- notes_user_id_fkey has no explicit ON DELETE clause, which means Postgres's
-- default: NO ACTION. Confirmed via pg_constraint.confdeltype = 'a'. This
-- means deleting an auth.users row while notes still reference it FAILS
-- outright (foreign-key violation) rather than silently orphaning rows --
-- app code (AuthManager.deleteAccount()) relies on deleting a user's notes
-- BEFORE calling the delete_user() RPC below, for exactly this reason.

-- No indexes beyond the primary key's implicit unique index (notes_pkey).
-- No triggers exist on this table.

-- ============================================================
-- Row Level Security
-- ============================================================

alter table public.notes enable row level security;

-- Covers SELECT/INSERT/UPDATE/DELETE. WITH CHECK is null in the live
-- database, which Postgres resolves by reusing the USING expression for
-- writes too -- inserts/updates are rejected unless the row's user_id
-- matches the caller, exactly like reads/deletes are filtered to it.
create policy "Users can only access their own notes"
  on public.notes for all
  using (auth.uid() = user_id);

-- Redundant with the policy above for UPDATE specifically (identical
-- condition) -- confirmed harmless since permissive policies are OR'd and
-- both sides of the OR are the same expression, but worth consolidating into
-- just the ALL policy above next time this file's owner is in here.
create policy "Users can update their own notes"
  on public.notes for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ============================================================
-- Account deletion
-- ============================================================

-- Self-scoped to auth.uid() -- takes no parameters, so it can never be used
-- to delete another user's account. search_path is pinned to defend against
-- search-path hijacking, the standard risk for SECURITY DEFINER functions.
create or replace function public.delete_user()
returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  delete from auth.users
  where id = auth.uid();
end;
$function$;
